NTPCLIENT_SOURCETREE = ntpclient-$(NTPCLIENT_UPSTREAM_VERSION)
NTPCLIENT_TARBALL = ntpclient_$(NTPCLIENT_UPSTREAM_VERSION)_365.tar.gz
NTPCLIENT_SOURCE = http://doolittle.icarus.com/ntpclient/$(NTPCLIENT_TARBALL)
