SFDISK_SOURCETREE = util-linux-$(SFDISK_UPSTREAM_VERSION)
SFDISK_TARBALL = util-linux-$(SFDISK_UPSTREAM_VERSION).tar.xz
SFDISK_SOURCE = https://www.kernel.org/pub/linux/utils/util-linux/v$(SFDISK_UPSTREAM_VERSION)/$(SFDISK_TARBALL)
