E2FSPROGS_SOURCETREE = e2fsprogs-$(E2FSPROGS_UPSTREAM_VERSION)
E2FSPROGS_TARBALL = e2fsprogs-$(E2FSPROGS_UPSTREAM_VERSION).tar.xz
E2FSPROGS_SOURCE = https://www.kernel.org/pub/linux/kernel/people/tytso/e2fsprogs/v$(E2FSPROGS_UPSTREAM_VERSION)/$(E2FSPROGS_TARBALL)
