#!/bin/sh

# Change root password to "password"
PASSWORD=$(echo -n password | cryptpw -m d -S aa)
VAULT=/root/etc/shadow
if [ ! -f "$VAULT" ]; then
  VAULT=/root/etc/passwd
fi
sed -i -e "s/^root:[^:]*/root:$PASSWORD/" "$VAULT"
echo "root password is 'password'"
