#!/bin/sh
#===========================
#FOR:BUILD
#===========================

#===========================
#FOR:RUN
#===========================

# Logging
NTP_PEER=ptbtime1.ptb.de
log_start "Getting time from $NTP_PEER..."

# Running ntpd
rdate -s $NTP_PEER
#ntpd -n -q -N -p $NTP_PEER 2>/dev/null
if [ $? -eq 0 ]; then
  log_ok
else
  log_fail
fi
