#!/bin/sh
#===========================
#FOR:BUILD
#===========================

require_versioned_package ntpclient ${NTPCLIENT_STRONG_VERSION}

#===========================
#FOR:RUN
#===========================

# Logging
NTP_PEER=pool.ntp.org
log_start "Getting time from $NTP_PEER..."

# Running ntpd
timeout 5 /bin/ntpclient -s -h $NTP_PEER >/dev/null 2>&1
if [ $? -eq 0 ]; then
  log_ok
else
  log_fail
fi
