#!/bin/sh
#===========================
#FOR:BUILD
#===========================

#===========================
#FOR:RUN
#===========================

UCONTEXT=${ROOT_RW}/context/ucontext
EXTRA_UCONTEXT=${ROOT_RW}/context/extra-ucontext

if [ -f ${UCONTEXT_TMP} ]; then
  mkdir -p ${ROOT_RW}/context
  mv ${UCONTEXT_TMP} ${UCONTEXT}
fi

if [ -f ${EXTRA_UCONTEXT_TMP} ]; then
  mkdir -p ${ROOT_RW}/context
  mv ${EXTRA_UCONTEXT_TMP} ${EXTRA_UCONTEXT}
fi

if [ -f ${EXTRA_PICKUP} ]; then
  mkdir -p ${ROOT_RW}/context
  cp ${EXTRA_PICKUP} ${ROOT_RW}/context/pickup.tar.gz
fi

[ -f ${UCONTEXT} ] && . ${UCONTEXT}
[ -f ${EXTRA_UCONTEXT} ] && . ${EXTRA_UCONTEXT}

