#!/bin/sh
#===========================
#FOR:BUILD
#===========================

#===========================
#FOR:RUN
#===========================

UCONTEXT=${ROOT_RW}/context/ucontext
EXTRA_UCONTEXT=${ROOT_RW}/context/extra-ucontext

if [ -f ${UCONTEXT_TMP} ]; then
  mkdir -p ${ROOT_RW}/context
  mv ${UCONTEXT_TMP} ${UCONTEXT}
fi

if [ -f ${EXTRA_UCONTEXT_TMP} ]; then
  mkdir -p ${ROOT_RW}/context
  mv ${EXTRA_UCONTEXT_TMP} ${EXTRA_UCONTEXT}
fi

if [ -f ${EXTRA_PICKUP} ]; then
  mkdir -p ${ROOT_RW}/context
  cp ${EXTRA_PICKUP} ${ROOT_RW}/context/pickup.tar.gz
fi

# Azure ejects the ISO image after provisioning, save it
if [ "x${AZURE_ISO}" != "x" ]; then
  mkdir -p ${ROOT_RW}/context
  dd if="${AZURE_ISO}" of="${ROOT_RW}/context/azure.iso" bs=1024 > /dev/null 2>&1
fi

[ -f ${UCONTEXT} ] && . ${UCONTEXT}
[ -f ${EXTRA_UCONTEXT} ] && . ${EXTRA_UCONTEXT}

