#!/bin/sh
#===========================
#FOR:RUN
#===========================

# This file contains all the hotfixes that the underlaying CVMFS filesystem 
# failed to provide. 

if [ -f ${ROOT}/.ucernvm_pinfiles ]; then
  log_start "Pinning core file set..."
  add_prefix=${AUFS_RO#${ROOT_RO}}
	result="$(client /${ROOT}/mnt/.rw/cache/${CVMFS_REPOS}/cvmfs_io.${CVMFS_REPOS} ${ROOT}/.ucernvm_pinfiles $add_prefix)"
  if [ "x$result" == "xNO" ]; then
    echo "failed pinning"
  fi
  log_ok
fi

