#!/bin/sh
#===========================
#FOR:BUILD
#===========================

#===========================
#FOR:RUN
#===========================

# Save log file on persistent storage

for logfile in /var/log/udhcpc.log /var/log/context.log; do
  if [ -f "$logfile" ]; then
    mkdir -p ${ROOT}/mnt/.rw/ulogs
    cp "$logfile" ${ROOT}/mnt/.rw/ulogs/
  fi
done

