#!/bin/sh
#===========================
#FOR:RUN
#===========================

# This file contains all the hotfixes that the underlaying CVMFS filesystem 
# failed to provide. 

# Change some critical permissions
chmod 1777 ${ROOT}/tmp
[ -f "${ROOT}/usr/bin/sudo" ] && chmod 4555 "${ROOT}/usr/bin/sudo"

# Create some missing folders
[ ! -d ${ROOT}/cvmfs ] && mkdir ${ROOT}/cvmfs

# Copy kernel modules
if [ ! -d ${ROOT}/lib/modules/$(uname -r) ]; then
  log_start "Posting kernel modules..."
  cp -a /lib/modules/$(uname -r) ${ROOT}/lib/modules
  log_ok
fi

# Fix mount.vmhgfs
for orig_mount in ${ROOT}/sbin/mount.vmhgfs ${ROOT}/usr/sbin/mount.vmhgfs; do
  if [ -f $orig_mount ]; then
    if ! diff -q $orig_mount ${ROOT}/lib/modules/$(uname -r)/kernel/fs/mount.vmhgfs >/dev/null 2>&1; then
      mv $orig_mount ${orig_mount}.orig
      cp ${ROOT}/lib/modules/$(uname -r)/kernel/fs/mount.vmhgfs $orig_mount
    fi
  fi
done

# Inject extra user data
if [ -f "${EXTRA_USER_DATA}" ]; then
  mkdir -p "${ROOT}$(dirname ${EXTRA_USER_DATA_INJECTED})"
  mv "${EXTRA_USER_DATA}" "${ROOT}${EXTRA_USER_DATA_INJECTED}"
fi

# Extract pickup tarball
if [ -f "${EXTRA_PICKUP}" ]; then
  sh -c "cd ${ROOT} && tar xzf ${EXTRA_PICKUP}"
fi

# Run bootstrap script provided by the repository
[ -f ${ROOT}/.ucernvm_bootstrap ] && . ${ROOT}/.ucernvm_bootstrap $ROOT
