PATCHELF_SOURCETREE = patchelf-$(PATCHELF_UPSTREAM_VERSION)
PATCHELF_TARBALL = patchelf-$(PATCHELF_UPSTREAM_VERSION).tar.gz
PATCHELF_SOURCE = https://github.com/NixOS/patchelf/archive/$(PATCHELF_UPSTREAM_VERSION).tar.gz
