DHCLIENT_SOURCETREE = dhcp-$(DHCLIENT_UPSTREAM_VERSION)
DHCLIENT_TARBALL = dhcp-$(DHCLIENT_UPSTREAM_VERSION).tar.gz
DHCLIENT_SOURCE = ftp://ftp.isc.org/isc/dhcp/$(DHCLIENT_UPSTREAM_VERSION)/$(DHCLIENT_TARBALL)
